from .base import *  # noqa

DEBUG = False

ALLOWED_HOSTS = [
    "backend.ochiapp.com",
    "www.backend.ochiapp.com",
]

CORS_ALLOWED_ORIGINS = []

HTTPS_ONLY = True
SECURE_SSL_REDIRECT = True
SECURE_HSTS_SECONDS = 31536000
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
