# Generated by Django 5.2.10 on 2026-02-04 13:10

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import properties.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("apartment", "Apartment"),
                            ("house", "House"),
                            ("townhouse", "Townhouse"),
                            ("commercial", "Commercial"),
                            ("land", "Land"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("address", models.CharField(max_length=255, unique=True)),
                (
                    "area",
                    models.DecimalField(
                        db_index=True,
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "property_class",
                    models.CharField(
                        choices=[
                            ("economy", "Economy"),
                            ("comfort", "Comfort"),
                            ("business", "Business"),
                            ("premium", "Premium"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        db_index=True,
                        decimal_places=2,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("currency", models.CharField(default="RUB", max_length=3)),
                ("deadline", models.DateField(blank=True, db_index=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=16,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="properties",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "property",
                "verbose_name_plural": "properties",
            },
        ),
        migrations.CreateModel(
            name="PropertyImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=properties.models.property_image_upload_to,
                    ),
                ),
                (
                    "external_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(db_index=True, default=0),
                ),
                ("is_primary", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "verbose_name": "property image",
                "verbose_name_plural": "property images",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["owner", "-created_at"], name="prop_owner_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(fields=["type", "price"], name="prop_type_price_idx"),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["status", "-created_at"], name="prop_status_created_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="property",
            constraint=models.CheckConstraint(
                condition=models.Q(("area__gt", 0)), name="prop_area_gt_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="property",
            constraint=models.CheckConstraint(
                condition=models.Q(("price__gte", 0)), name="prop_price_gte_0"
            ),
        ),
        migrations.AddIndex(
            model_name="propertyimage",
            index=models.Index(
                fields=["property", "sort_order"], name="pimg_prop_sort_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="propertyimage",
            constraint=models.UniqueConstraint(
                fields=("property", "sort_order"), name="pimg_unique_sort_per_property"
            ),
        ),
        migrations.AddConstraint(
            model_name="propertyimage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("property",),
                name="pimg_one_primary_per_property",
            ),
        ),
        migrations.AddConstraint(
            model_name="propertyimage",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("image__isnull", False),
                    ("external_url__isnull", False),
                    _connector="OR",
                ),
                name="pimg_requires_image_or_url",
            ),
        ),
    ]
