# Generated by Django 5.2.10 on 2026-02-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="moderation_status",
            field=models.CharField(
                choices=[
                    ("in_review", "In review"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                db_index=True,
                default="in_review",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("published", "Published"),
                    ("archived", "Archived"),
                    ("sold", "Sold"),
                ],
                db_index=True,
                default="draft",
                max_length=16,
            ),
        ),
    ]
