# Generated by Django 5.2.10 on 2026-02-14 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0002_property_moderation_status_alter_property_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="moderation_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                db_index=True,
                default="pending",
                max_length=16,
            ),
        ),
    ]
