# Generated by Django 5.2.10 on 2026-03-25 08:54

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0003_alter_property_moderation_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="property",
            options={"verbose_name": "Объект", "verbose_name_plural": "Объекты"},
        ),
        migrations.AlterField(
            model_name="property",
            name="address",
            field=models.CharField(max_length=255, unique=True, verbose_name="Адрес"),
        ),
        migrations.AlterField(
            model_name="property",
            name="area",
            field=models.DecimalField(
                db_index=True,
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="Площадь",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="currency",
            field=models.CharField(default="RUB", max_length=3, verbose_name="Валюта"),
        ),
        migrations.AlterField(
            model_name="property",
            name="deadline",
            field=models.DateField(
                blank=True, db_index=True, null=True, verbose_name="Дедлайн"
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="moderation_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                db_index=True,
                default="pending",
                max_length=16,
                verbose_name="Статус модерации",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="price",
            field=models.DecimalField(
                db_index=True,
                decimal_places=2,
                max_digits=14,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Цена",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="property_class",
            field=models.CharField(
                choices=[
                    ("economy", "Economy"),
                    ("comfort", "Comfort"),
                    ("business", "Business"),
                    ("premium", "Premium"),
                ],
                db_index=True,
                max_length=32,
                verbose_name="Класс объекта",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("published", "Published"),
                    ("archived", "Archived"),
                    ("sold", "Sold"),
                ],
                db_index=True,
                default="draft",
                max_length=16,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="type",
            field=models.CharField(
                choices=[
                    ("apartment", "Apartment"),
                    ("house", "House"),
                    ("townhouse", "Townhouse"),
                    ("commercial", "Commercial"),
                    ("land", "Land"),
                ],
                db_index=True,
                max_length=32,
                verbose_name="Тип",
            ),
        ),
    ]
