# Generated by Django 5.2.10 on 2026-03-26 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0004_alter_property_options_alter_property_address_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="property",
            name="currency",
        ),
    ]
