# Generated by Django 5.2.10 on 2026-03-27 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0005_remove_property_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="moderation_rejection_reason",
            field=models.CharField(
                blank=True,
                max_length=1000,
                null=True,
                verbose_name="Причина отказа модерации",
            ),
        ),
    ]
