# Generated by Django 5.2.10 on 2026-03-27 12:48

from django.conf import settings
from django.db import migrations, models
from django.db.models import Q


def fix_property_class_before_constraint(apps, schema_editor):
    Property = apps.get_model("properties", "Property")

    # Для land property_class должен быть пустым
    Property.objects.filter(type="land").exclude(
        Q(property_class__isnull=True) | Q(property_class="")
    ).update(property_class=None)

    # Для остальных типов property_class должен быть заполнен
    # Если у тебя по бизнес-логике нужно другое значение — замени "economy"
    Property.objects.exclude(type="land").filter(
        Q(property_class__isnull=True) | Q(property_class="")
    ).update(property_class="economy")


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0006_property_moderation_rejection_reason"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="property_class",
            field=models.CharField(
                blank=True,
                choices=[
                    ("economy", "Economy"),
                    ("comfort", "Comfort"),
                    ("business", "Business"),
                    ("premium", "Premium"),
                ],
                db_index=True,
                max_length=32,
                null=True,
                verbose_name="Класс объекта",
            ),
        ),
        migrations.RunPython(
            fix_property_class_before_constraint,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="property",
            constraint=models.CheckConstraint(
                condition=(
                    (
                        Q(type="land")
                        & (Q(property_class__isnull=True) | Q(property_class=""))
                    )
                    | (
                        ~Q(type="land")
                        & Q(property_class__isnull=False)
                        & ~Q(property_class="")
                    )
                ),
                name="prop_land_property_class_rule",
            ),
        ),
    ]
