# Generated by Django 5.2.10 on 2026-03-27 12:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0006_property_moderation_rejection_reason"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="property_class",
            field=models.CharField(
                blank=True,
                choices=[
                    ("economy", "Economy"),
                    ("comfort", "Comfort"),
                    ("business", "Business"),
                    ("premium", "Premium"),
                ],
                db_index=True,
                max_length=32,
                null=True,
                verbose_name="Класс объекта",
            ),
        ),
        migrations.AddConstraint(
            model_name="property",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("type", "land"),
                        models.Q(
                            ("property_class__isnull", True),
                            ("property_class", ""),
                            _connector="OR",
                        ),
                    ),
                    models.Q(
                        models.Q(("type", "land"), _negated=True),
                        ("property_class__isnull", False),
                        models.Q(("property_class", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="prop_land_property_class_rule",
            ),
        ),
    ]
