# Generated by Django 5.2.10 on 2026-04-02 07:29

import uuid

from django.conf import settings
from django.db import migrations, models


def fill_property_reference_ids(apps, schema_editor):
    Property = apps.get_model("properties", "Property")

    for prop in Property.objects.filter(reference_id__isnull=True):
        prop.reference_id = uuid.uuid4()
        prop.save(update_fields=["reference_id"])


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0008_property_commission_rate"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="delivery_date",
            field=models.DateField(
                blank=True, db_index=True, null=True, verbose_name="Дата сдачи"
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="project",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=255,
                null=True,
                verbose_name="Проект",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="purpose",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=255,
                null=True,
                verbose_name="Назначение",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="reference_id",
            field=models.UUIDField(
                null=True,
                blank=True,
                editable=False,
                db_index=True,
            ),
        ),
        migrations.RunPython(fill_property_reference_ids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="property",
            name="reference_id",
            field=models.UUIDField(
                default=uuid.uuid4,
                unique=True,
                editable=False,
                db_index=True,
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="rooms",
            field=models.PositiveSmallIntegerField(
                blank=True, db_index=True, null=True, verbose_name="Комнат"
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(fields=["reference_id"], name="prop_reference_id_idx"),
        ),
    ]
