# Generated by Django 5.2.10 on 2026-04-07 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0009_property_delivery_date_property_project_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="developer_name",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Застройщик"
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="floor",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Этаж"
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="house_number",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="Номер дома"
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="land_number",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="Номер участка"
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="address",
            field=models.CharField(db_index=True, max_length=255, verbose_name="Адрес"),
        ),
    ]
