# Generated by Django 5.2.10 on 2026-04-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0010_property_developer_name_property_floor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="project_comment",
            field=models.TextField(
                blank=True, default="", verbose_name="Комментарий к проекту"
            ),
        ),
    ]
