# Generated by Django 5.2.10 on 2026-04-14 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0011_property_project_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="show_price_to_brokers",
            field=models.BooleanField(
                default=True, verbose_name="Показывать прайсовую цену брокерам"
            ),
        ),
    ]
