# Generated by Django 5.2.10 on 2026-04-14 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0012_property_show_price_to_brokers"),
        ("properties", "0013_property_commercial_subtype"),
    ]

    operations = []
