# Generated by Django 5.2.10 on 2026-04-18 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0014_merge_20260414_0512"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="property",
            name="show_price_to_brokers",
        ),
    ]
