# Generated by Django 5.2.10 on 2026-02-06 16:20

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("properties", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Auction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("open", "Open"), ("closed", "Closed")],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                (
                    "min_price",
                    models.DecimalField(
                        db_index=True,
                        decimal_places=2,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("start_date", models.DateTimeField(db_index=True)),
                ("end_date", models.DateTimeField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("finished", "Finished"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=12,
                    ),
                ),
                ("bids_count", models.PositiveIntegerField(default=0)),
                (
                    "current_price",
                    models.DecimalField(
                        db_index=True,
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_auctions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "real_property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auctions",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Bid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        db_index=True,
                        decimal_places=2,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "auction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bids",
                        to="auctions.auction",
                    ),
                ),
                (
                    "broker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bids",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="auction",
            name="highest_bid",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="as_highest_for_auctions",
                to="auctions.bid",
            ),
        ),
        migrations.AddField(
            model_name="auction",
            name="winner_bid",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="as_winner_for_auctions",
                to="auctions.bid",
            ),
        ),
        migrations.AddIndex(
            model_name="bid",
            index=models.Index(
                fields=["auction", "-created_at"], name="bid_auc_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bid",
            index=models.Index(
                fields=["auction", "-amount"], name="bid_auc_amount_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bid",
            index=models.Index(
                fields=["broker", "-created_at"], name="bid_broker_created_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="bid",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", Decimal("0.00"))),
                name="bid_amount_gt_0",
            ),
        ),
        migrations.AddIndex(
            model_name="auction",
            index=models.Index(
                fields=["status", "end_date"], name="auc_status_end_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auction",
            index=models.Index(
                fields=["mode", "status", "end_date"], name="auc_mode_status_end_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auction",
            index=models.Index(
                fields=["real_property", "-created_at"], name="auc_prop_created_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="auction",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_date__gt", models.F("start_date"))),
                name="auc_end_gt_start",
            ),
        ),
        migrations.AddConstraint(
            model_name="auction",
            constraint=models.CheckConstraint(
                condition=models.Q(("min_price__gte", Decimal("0.00"))),
                name="auc_min_price_gte_0",
            ),
        ),
    ]
