# Generated by Django 5.2.10 on 2026-02-11 06:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="auction",
            name="auc_status_end_idx",
        ),
        migrations.RemoveIndex(
            model_name="auction",
            name="auc_mode_status_end_idx",
        ),
        migrations.RemoveIndex(
            model_name="auction",
            name="auc_prop_created_idx",
        ),
        migrations.RemoveIndex(
            model_name="bid",
            name="bid_auc_created_idx",
        ),
        migrations.RemoveIndex(
            model_name="bid",
            name="bid_auc_amount_idx",
        ),
        migrations.RemoveIndex(
            model_name="bid",
            name="bid_broker_created_idx",
        ),
        migrations.AddField(
            model_name="auction",
            name="shortlisted_bids",
            field=models.ManyToManyField(
                blank=True, related_name="shortlisted_in_auctions", to="auctions.bid"
            ),
        ),
        migrations.AddField(
            model_name="bid",
            name="is_sealed",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="bid",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddConstraint(
            model_name="bid",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_sealed", True)),
                fields=("auction", "broker"),
                name="bid_unique_sealed_per_broker_per_auction",
            ),
        ),
    ]
