# Generated by Django 5.2.10 on 2026-02-11 06:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_remove_auction_auc_status_end_idx_and_more"),
        ("properties", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="auction",
            name="shortlisted_bids",
        ),
        migrations.RemoveField(
            model_name="bid",
            name="updated_at",
        ),
        migrations.AddIndex(
            model_name="auction",
            index=models.Index(
                fields=["status", "end_date"], name="auc_status_end_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auction",
            index=models.Index(
                fields=["mode", "status", "end_date"], name="auc_mode_status_end_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auction",
            index=models.Index(
                fields=["real_property", "-created_at"], name="auc_prop_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auction",
            index=models.Index(
                fields=["owner", "-created_at"], name="auc_owner_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bid",
            index=models.Index(
                fields=["auction", "-created_at"], name="bid_auc_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bid",
            index=models.Index(
                fields=["auction", "-amount"], name="bid_auc_amount_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bid",
            index=models.Index(
                fields=["broker", "-created_at"], name="bid_broker_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bid",
            index=models.Index(fields=["auction", "broker"], name="bid_auc_broker_idx"),
        ),
    ]
