# Generated by Django 5.2.10 on 2026-02-11 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0003_remove_auction_shortlisted_bids_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="shortlisted_bids",
            field=models.ManyToManyField(
                blank=True, related_name="shortlisted_in_auctions", to="auctions.bid"
            ),
        ),
    ]
