# Generated by Django 5.2.10 on 2026-03-25 09:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0005_alter_auction_status"),
        ("properties", "0004_alter_property_options_alter_property_address_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="auction",
            constraint=models.UniqueConstraint(
                fields=("real_property",), name="unique_auction_per_property"
            ),
        ),
    ]
