# Generated by Django 5.2.10 on 2026-03-27 07:15

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0007_auction_min_bid_increment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction",
            name="min_bid_increment",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Минимальный шаг повышения ставки для open-аукциона.",
                max_digits=14,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("1.00"))],
            ),
        ),
    ]
