# Generated by Django 5.2.10 on 2026-04-01 14:30

from decimal import Decimal

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0008_alter_auction_min_bid_increment"),
        ("properties", "0008_property_commission_rate"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuctionProperty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "auction_properties",
            },
        ),
        migrations.RemoveConstraint(
            model_name="auction",
            name="unique_auction_per_property",
        ),
        migrations.RemoveConstraint(
            model_name="auction",
            name="auc_open_requires_increment_closed_null",
        ),
        migrations.RenameIndex(
            model_name="auction",
            new_name="auc_open_prop_created_idx",
            old_name="auc_prop_created_idx",
        ),
        migrations.AlterField(
            model_name="auction",
            name="real_property",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="open_auctions",
                to="properties.property",
            ),
        ),
        migrations.AddField(
            model_name="auctionproperty",
            name="auction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="auction_properties",
                to="auctions.auction",
            ),
        ),
        migrations.AddField(
            model_name="auctionproperty",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="auction_links",
                to="properties.property",
            ),
        ),
        migrations.AddField(
            model_name="auction",
            name="properties",
            field=models.ManyToManyField(
                blank=True,
                related_name="lot_auctions",
                through="auctions.AuctionProperty",
                to="properties.property",
            ),
        ),
        migrations.AddConstraint(
            model_name="auction",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("mode", "open"),
                        ("min_bid_increment__isnull", False),
                        ("min_bid_increment__gte", Decimal("1.00")),
                        ("real_property__isnull", False),
                    ),
                    models.Q(("mode", "closed"), ("min_bid_increment__isnull", True)),
                    _connector="OR",
                ),
                name="auc_open_requires_increment_and_property",
            ),
        ),
        migrations.AddIndex(
            model_name="auctionproperty",
            index=models.Index(
                fields=["auction", "property"], name="aucprop_auc_prop_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auctionproperty",
            index=models.Index(fields=["property"], name="aucprop_prop_idx"),
        ),
        migrations.AddConstraint(
            model_name="auctionproperty",
            constraint=models.UniqueConstraint(
                fields=("auction", "property"), name="aucprop_unique_auction_property"
            ),
        ),
    ]
