# Generated by Django 5.2.10 on 2026-04-14 04:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0009_auctionproperty_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="bid",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddConstraint(
            model_name="bid",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_sealed", False)),
                fields=("auction", "broker"),
                name="bid_unique_open_per_broker_per_auction",
            ),
        ),
    ]
