# Generated by Django 5.2.10 on 2026-04-16 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0011_bid_unique_open_per_broker_constraint"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="owner_decided_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="auction",
            name="owner_decision",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("rejected", "Rejected"),
                ],
                db_index=True,
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="auction",
            name="owner_rejection_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="auction",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Scheduled"),
                    ("active", "Active"),
                    ("finished", "Finished"),
                    ("cancelled", "Cancelled"),
                    ("failed", "Failed"),
                ],
                db_index=True,
                default="scheduled",
                max_length=12,
            ),
        ),
    ]
