# Generated by Django 5.2.10 on 2026-04-16 06:40

import auctions.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0012_add_owner_decision_and_failed_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание запроса")),
                (
                    "broker_comment",
                    models.TextField(
                        blank=True, default="", verbose_name="Комментарий брокера"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("answered", "Answered"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("answered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "auction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_requests",
                        to="auctions.auction",
                    ),
                ),
                (
                    "broker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="received_document_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sent_document_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Запрос документов",
                "verbose_name_plural": "Запросы документов",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentRequestFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=auctions.models.document_request_upload_to
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="response_documents",
                        to="auctions.documentrequest",
                    ),
                ),
            ],
            options={
                "ordering": ["uploaded_at"],
            },
        ),
        migrations.AddIndex(
            model_name="documentrequest",
            index=models.Index(
                fields=["auction", "-created_at"], name="docreq_auc_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentrequest",
            index=models.Index(
                fields=["broker", "status"], name="docreq_broker_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentrequestfile",
            index=models.Index(
                fields=["request", "uploaded_at"], name="docreqfile_req_up_idx"
            ),
        ),
    ]
