# Generated by Django 5.2.10 on 2026-04-16 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0013_add_document_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="declined_bids",
            field=models.ManyToManyField(
                blank=True, related_name="declined_in_auctions", to="auctions.bid"
            ),
        ),
    ]
