# Generated by Django 5.2.10 on 2026-04-18 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0014_auction_declined_bids"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="show_price_to_brokers",
            field=models.BooleanField(default=True),
        ),
    ]
