# Generated by Django 5.2.10 on 2026-04-19 07:30

import django.db.models.deletion
import django.utils.timezone
import payments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deals", "0004_alter_deal_status_alter_deallog_action"),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DealSettlement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "broker_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        verbose_name="К выплате брокеру",
                    ),
                ),
                (
                    "broker_rate",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Ставка брокера (%)",
                    ),
                ),
                (
                    "platform_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        verbose_name="Комиссия платформы",
                    ),
                ),
                (
                    "platform_rate",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Ставка платформы (%)",
                    ),
                ),
                (
                    "total_from_developer",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="broker_amount + platform_amount",
                        max_digits=14,
                        verbose_name="Долг девелопера",
                    ),
                ),
                ("paid_to_broker", models.BooleanField(db_index=True, default=False)),
                ("paid_to_broker_at", models.DateTimeField(blank=True, null=True)),
                (
                    "broker_payout_receipt",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=payments.models.broker_payout_receipt_upload_to,
                        verbose_name="Чек выплаты брокеру",
                    ),
                ),
                ("broker_payout_deadline", models.DateTimeField(db_index=True)),
                (
                    "received_from_developer",
                    models.BooleanField(db_index=True, default=False),
                ),
                (
                    "received_from_developer_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "developer_receipt",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=payments.models.developer_receipt_upload_to,
                        verbose_name="Чек девелопера",
                    ),
                ),
                (
                    "developer_receipt_uploaded_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("developer_payment_deadline", models.DateTimeField(db_index=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deal",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="settlement",
                        to="deals.deal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Расчёт по сделке",
                "verbose_name_plural": "Расчёты по сделкам",
                "ordering": ["-created_at"],
            },
        ),
    ]
