# Generated by Django 5.2.10 on 2026-02-04 06:10

from django.db import migrations, models

import apps.users.validators


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="broker",
            name="inn_number",
            field=models.CharField(
                max_length=12,
                unique=True,
                validators=[apps.users.validators.validate_inn],
            ),
        ),
    ]
