# Generated by Django 5.2.10 on 2026-02-02 11:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20, verbose_name='verification status'),
        ),
        migrations.AlterField(
            model_name='broker',
            name='is_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('developer', 'Developer'), ('broker', 'Broker'), ('admin', 'Admin')], db_index=True, default='developer', max_length=20, verbose_name='role'),
        ),
        migrations.AddIndex(
            model_name='broker',
            index=models.Index(fields=['is_verified', 'verified_at'], name='users_broke_is_veri_313ebf_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'is_active'], name='users_user_role_e1ec1a_idx'),
        ),
    ]
