# Generated by Django 5.2.10 on 2026-02-04 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_broker_inn_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="broker",
            name="rejected_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
