# Generated by Django 5.2.10 on 2026-02-03 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_developer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='broker',
            old_name='verification_document',
            new_name='passport',
        ),
    ]
