# Generated by Django 5.2.10 on 2026-03-23 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_broker_rejected_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="broker",
            name="inn_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="broker",
            name="passport_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
