# Generated by Django 5.2.10 on 2026-03-26 04:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.users.models
import apps.users.validators


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_broker_inn_name_broker_passport_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="broker",
            name="inn",
        ),
        migrations.RemoveField(
            model_name="broker",
            name="inn_name",
        ),
        migrations.RemoveField(
            model_name="broker",
            name="inn_number",
        ),
        migrations.RemoveField(
            model_name="broker",
            name="passport",
        ),
        migrations.RemoveField(
            model_name="broker",
            name="passport_name",
        ),
        migrations.AddField(
            model_name="user",
            name="inn_number",
            field=models.CharField(
                blank=True,
                max_length=12,
                null=True,
                unique=True,
                validators=[apps.users.validators.validate_inn],
            ),
        ),
        migrations.CreateModel(
            name="UserDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document",
                    models.FileField(upload_to=apps.users.models.user_document_folder),
                ),
                ("document_name", models.CharField(blank=True, max_length=255)),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("inn", "ИНН"),
                            ("passport", "Паспорт"),
                            ("others", "Другие"),
                        ],
                        max_length=15,
                        verbose_name="тип документа",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "документ пользователя",
                "verbose_name_plural": "документы пользователя",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "doc_type"],
                        name="users_userd_user_id_6d95a3_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="users_userd_user_id_e201fd_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("doc_type__in", ["inn", "passport"])),
                        fields=("user", "doc_type"),
                        name="uniq_user_single_primary_doc_type",
                    )
                ],
            },
        ),
    ]
