# Generated by Django 5.2.10 on 2026-03-27 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_remove_broker_inn_remove_broker_inn_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="broker",
            name="rejection_reason",
            field=models.CharField(
                blank=True, max_length=1000, null=True, verbose_name="rejection reason"
            ),
        ),
    ]
