# Generated by Django 5.2.10 on 2026-04-07 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_broker_rejection_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="broker",
            name="phone_number",
            field=models.CharField(
                blank=True, default="", max_length=20, verbose_name="phone number"
            ),
        ),
    ]
