# Generated by Django 5.2.10 on 2026-04-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_broker_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="developer",
            name="phone_number",
            field=models.CharField(
                blank=True, default="", max_length=20, verbose_name="phone number"
            ),
        ),
    ]
