# Generated by Django 5.2.10 on 2026-04-27 02:40

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_developer_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='ddu_template',
            field=models.FileField(blank=True, null=True, upload_to=apps.users.models.developer_ddu_template_folder, verbose_name='Шаблон ДДУ'),
        ),
    ]
