# Generated by Django 5.2.10 on 2026-04-28 10:50

import helpers.encrypted_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_developer_ddu_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broker',
            name='phone_number',
            field=helpers.encrypted_fields.EncryptedCharField(blank=True, default='', max_length=128, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='phone_number',
            field=helpers.encrypted_fields.EncryptedCharField(blank=True, default='', max_length=128, verbose_name='phone number'),
        ),
    ]
