# Generated by Django 5.2.10 on 2026-04-01 14:30

from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0009_auctionproperty_and_more"),
        ("deals", "0001_initial"),
        ("properties", "0008_property_commission_rate"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="deal",
            name="lot_bid_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=14,
                null=True,
                verbose_name="Ставка по лоту",
            ),
        ),
        migrations.AlterField(
            model_name="deal",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=14, verbose_name="Сумма сделки"
            ),
        ),
        migrations.AlterField(
            model_name="deal",
            name="bid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="deals",
                to="auctions.bid",
            ),
        ),
        migrations.AddIndex(
            model_name="deal",
            index=models.Index(
                fields=["auction", "real_property"], name="deal_auc_prop_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="deal",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("lot_bid_amount__isnull", True),
                    ("lot_bid_amount__gt", Decimal("0.00")),
                    _connector="OR",
                ),
                name="deal_lot_bid_amount_gt_0_or_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="deal",
            constraint=models.UniqueConstraint(
                fields=("auction", "real_property"), name="deal_unique_auction_property"
            ),
        ),
    ]
