# Generated by Django 5.2.10 on 2026-04-16 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deals", "0002_deal_lot_bid_amount_alter_deal_amount_alter_deal_bid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deal",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_documents", "Pending Documents"),
                    ("admin_review", "Admin Review"),
                    ("developer_confirm", "Developer Confirm"),
                    ("confirmed", "Confirmed"),
                    ("failed", "Failed"),
                ],
                db_index=True,
                default="pending_documents",
                max_length=20,
                verbose_name="Статус сделки",
            ),
        ),
        migrations.AlterField(
            model_name="deallog",
            name="action",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("ddu_uploaded", "DDU Uploaded"),
                    ("payment_proof_uploaded", "Payment Proof Uploaded"),
                    ("comment_added", "Comment Added"),
                    ("submitted_for_review", "Submitted for Review"),
                    ("admin_approved", "Admin Approved"),
                    ("admin_rejected", "Admin Rejected"),
                    ("developer_confirmed", "Developer Confirmed"),
                    ("developer_rejected", "Developer Rejected"),
                    ("marked_overdue", "Marked Overdue"),
                    ("marked_failed", "Marked Failed"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
    ]
